- src/music-player/musicapp.cpp
修复自动播放打开时，启动播放器，播放音乐正常但 MPRIS 信息未能成功初始化的问题。
原因是自动播放是先进行的， MPRIS 是在其后进行的初始化（并连接了相应信号和槽），于是播放时的信号没能成功与槽关联导致没有初始化 MPRIS 数据。
https://tower.im/teams/9487/todos/232998/
> fix: do init MPRIS first

- src/plugin/plugin.pro
> fix: no longer build netease meta search plugin

- src/music-player/main.cpp
- src/music-player/musicapp.cpp
- src/music-player/musicapp.h
上个提交调整顺序引入了双击播放文件无法正常播放的bug（初始化顺序导致的信号没连上），这个提交可以修复这个问题，并且应该可以再改善一点启动速度（
> fix: init music app connection after init player

- src/music-player/listView/albumList/albumlistview.cpp
- src/music-player/listView/singerList/singerlistview.cpp
设置专辑、演唱者一级列表只能单选
Log: 取消专辑、演唱者一级列表的多选能力
Bug: https://pms.uniontech.com/bug-view-112583.html
> fix: 专辑和演唱者列表不支持自定义排序但又支持多选容易让用户疑惑

- CMakeLists.txt
Fix https://github.com/linuxdeepin/developer-center/issues/2232
> Fix build on x86_64: add fPIC option

- src/libdmusic/metadetector.cpp
添加判断音乐ID3v2Tag
Log: Qt播放器时正常启动
> fix: 音乐不存在ID3v2Tag问题

- src/music-player/mainFrame/musiclistdatawidget.cpp
- src/music-player/mainFrame/musiclistdatawidget.h
启动延迟未刷新歌曲数目
Log: 音乐每次启动歌曲数目正常
Bug: https://pms.uniontech.com/bug-view-123073.html
> fix: 音乐每次启动的时候所有音乐均显示为15首歌曲

- src/music-player/core/player.cpp
- src/music-player/core/playerbase.h
暂停时未将歌曲设置到播放器
Log: 播放演唱者或专辑歌曲正常
Bug: https://pms.uniontech.com/bug-view-123303.html
> fix: 演唱者或专辑页面详情页面播放任意歌曲后暂停然后删除歌曲后继续播放的歌曲为删除掉的歌曲

- src/libdmusic/metadetector.cpp
- src/music-player/core/player.cpp
- src/music-player/core/playerbase.h
- src/music-player/core/qtplayer.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
切换歌曲时终止上一首歌曲并重新计算下一首索引
Log: 切换歌曲正常
Bug: https://pms.uniontech.com/bug-view-122595.html,https://pms.uniontech.com/bug-view-122845.html,https://pms.uniontech.com/bug-view-122897.html,https://pms.uniontech.com/bug-view-122913.html
> fix: 切换歌曲时未终止上一首歌曲

- src/music-player/core/vlcplayer.cpp
- src/music-player/widget/lrc/musiclyricwidget.cpp
gstreamer歌词界面没有展示歌曲封面
Log: gstreamer歌词界面没有展示歌曲封面
Bug: https://pms.uniontech.com/bug-view-122579.html
> fix: gstreamer歌词界面没有展示歌曲封面

- src/music-player/core/vlc/Instance.cpp
- src/music-player/core/vlcplayer.cpp
- src/music-player/presenter/dboperate.cpp
- tests/test-prj-running.sh
添加不支持的歌曲时提示框弹出时间较长
Log: 添加不支持的歌曲时提示框弹出时间较长
Bug: https://pms.uniontech.com/bug-view-122953.html
https://pms.uniontech.com/bug-view-123071.html
> fix: 添加不支持的歌曲时提示框弹出时间较长

- src/music-player/listView/singerList/singerdelegate.cpp
平铺模式下放歌时设置当前播放列表为专辑
Log: 平铺模式下放歌正常
> fix: 在演唱者的平铺模式下放歌左侧音乐库的动画效果展示在专辑栏上

- src/music-player/mainFrame/mainframe.cpp
直接打开文件时未进行设置均衡器
Log: 均衡器效果正常
Bug: https://pms.uniontech.com/bug-view-124511.html
> fix: 在文官中打开歌曲后无法触发均衡器效果

- src/music-player/presenter/databaseservice.cpp
删除所有歌曲时，右键点击左侧音乐库任意项时，删除的滚动效果就消失了
Log: 删除所有歌曲时，右键点击左侧音乐库任意项时，删除的滚动效果就消失了
Bug: https://pms.uniontech.com/bug-view-122967.html
> fix: 删除所有歌曲时，右键点击左侧音乐库任意项时，删除的滚动效果就消失了

- src/music-player/core/qtplayer.cpp
跳过播放无效音乐文件
Log: 正常跳过无效音乐文件
Bug: https://pms.uniontech.com/bug-view-122845.html
> fix: 遇到歌曲本身有问题的歌曲音乐不会自动跳过

- src/music-player/mainFrame/musiclistdatawidget.cpp
延迟加载后重新刷新歌曲数目
Log: 外部打开音乐歌曲显示正常
Bug: https://pms.uniontech.com/bug-view-125431.html
> fix: 在文管中选中点击打开调起音乐后所有音乐界面展示歌曲数量错误

- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
- tests/testApplication.cpp
窗口显示状态错误
Log: 托盘正常唤起音乐
Bug: https://pms.uniontech.com/bug-view-124509.html
> fix: 托盘音乐图标点击多次后无法唤起音乐窗口

- src/music-player/core/musicsettings.cpp
- src/music-player/core/musicsettings.h
- src/music-player/mainFrame/mainframe.cpp
选择保存当前播放进度不生效
Log: 选择保存当前播放进度不生效
Bug: https://pms.uniontech.com/bug-view-127359.html
> fix: 选择保存当前播放进度不生效

- src/music-player/main.cpp
终端使用deepin-music加歌曲后，音乐不会播放加的歌曲
Log: 终端使用deepin-music加歌曲后，音乐不会播放加的歌曲
Bug: https://pms.uniontech.com/bug-view-127339.html
> fix: 终端使用deepin-music加歌曲后，音乐不会播放加的歌曲

- src/music-player/mainFrame/subsonglistwidget.cpp
专辑或演唱者详情里面的播放所有与其他地方的播放所有表现不一致
Log: 专辑或演唱者详情里面的播放所有与其他地方的播放所有表现不一致
Bug: https://pms.uniontech.com/bug-view-127313.html
> fix: 专辑或演唱者详情里面的播放所有与其他地方的播放所有表现不一致

- src/music-player/listView/albumList/albumlistview.cpp
- src/music-player/listView/albumList/albumlistview.h
- src/music-player/listView/singerList/singerlistview.cpp
- src/music-player/listView/singerList/singerlistview.h
播放任意搜索的歌曲后，去专辑页面播放任意歌曲后，删除当前专辑中的歌曲，音乐没有继续播放下一首歌曲
Log: 播放任意搜索的歌曲后，去专辑页面播放任意歌曲后，删除当前专辑中的歌曲，音乐没有继续播放下一首歌曲
Bug: https://pms.uniontech.com/bug-view-125751.html
> fix: 播放任意搜索的歌曲后，去专辑页面播放任意歌曲后，删除当前专辑中的歌曲，音乐没有继续播放下一首歌曲

- src/music-player/listView/albumList/albumlistview.cpp
- src/music-player/listView/albumList/albumlistview.h
- src/music-player/listView/singerList/singerlistview.cpp
- src/music-player/listView/singerList/singerlistview.h
播放任意搜索歌曲后，播放任意专辑后删除专辑中的所有歌曲没有自动跳转到下一张专辑播放
Log: 播放任意搜索歌曲后，播放任意专辑后删除专辑中的所有歌曲没有自动跳转到下一张专辑播放
Bug: https://pms.uniontech.com/bug-view-126059.html
> fix: 播放任意搜索歌曲后，播放任意专辑后删除专辑中的所有歌曲没有自动跳转到下一张专辑播放

- src/music-player/listView/musicInfoList/playlistview.cpp
使用ffmpeg解码库播放CD，音乐也会显示不支持此编码的提示语
Log: 使用ffmpeg解码库播放CD，音乐也会显示不支持此编码的提示语
Bug: https://pms.uniontech.com/bug-view-125879.html
> fix: 使用ffmpeg解码库播放CD，音乐也会显示不支持此编码的提示语

- src/music-player/core/vlc/Media.cpp
初始化音乐时将当前路径置为空了
Log: 正常播放暂停音乐
Bug: https://pms.uniontech.com/bug-view-129681.html
> fix: 暂停歌曲后继续播放歌曲会从头开始播放

- src/music-player/core/qtplayer.cpp
- src/music-player/mainFrame/mainframe.cpp
【AMD, ARM】音乐关闭主窗口时，选择退出，不再询问后，再次退出仍弹窗询问
Log: 【AMD, ARM】音乐关闭主窗口时，选择退出，不再询问后，再次退出仍弹窗询问
Bug: https://pms.uniontech.com/bug-view-129637.html
> fix: 【AMD, ARM】音乐关闭主窗口时，选择退出，不再询问后，再次退出仍弹窗询问

- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
窗口特效关闭后需要使用showNormal/showMaximized
Log: 音乐的托盘唤醒正常
Bug: https://pms.uniontech.com/bug-view-127663.html
> fix: 窗口特效关闭后音乐的托盘按钮只有第一次能正常唤起音乐

- src/music-player/core/metabufferdetector.cpp
- src/music-player/main.cpp
双击打开时导入数据时未进行播放器判断
Log: 正常播放歌曲
Bug: https://pms.uniontech.com/bug-view-132843.html
> fix: 使用ffmpeg解码库的时从文管直接双击打开歌曲会使音乐中部分已有的歌曲无法播放

- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
添加重命名不删除操作
Log: 重命名不删除歌单
Bug: https://pms.uniontech.com/bug-view-137279.html
> fix: 歌单重命名时使用delete键不是删除文字是删除歌单

- src/music-player/widget/closeconfirmdialog.cpp
修复单选按钮选中状态显示截断问题
Bug: https://pms.uniontech.com/bug-view-134093.html
Log: no
> fix: 修复单选按钮选中状态显示截断

- src/music-player/listView/musicInfoList/playlistview.cpp
延迟加载时取消重复加载相同歌曲
Log: 文官打开歌曲显示歌曲数目正常
Bug: https://pms.uniontech.com/bug-view-135241.html
> fix: 在文管中双击打开歌曲后音乐中显示歌曲增加2

- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/mainFrame/footerwidget.cpp
- src/music-player/mainFrame/footerwidget.h
修复双击播放歌曲工具栏无法展示歌曲图片，拖拽显示问题
Log: 修复双击播放歌曲工具栏无法展示歌曲图片，拖拽显示问题
Bug: https://pms.uniontech.com/bug-view-173653.html
https://pms.uniontech.com/bug-view-155789.html
> fix: 双击播放歌曲，工具栏无法展示歌曲图片

- src/music-player/mainwindow/WindowTitlebar.qml
标题栏退出菜单改为直接退出，不进行二次询问
Log: 标题栏退出菜单改为直接退出，不进行二次询问
> fix: 标题栏退出菜单无法直接退出

- src/music-player/allItems/Shortcuts.qml
当前播放歌曲为空时,禁用添加到喜欢的快捷键
Log: 当前播放歌曲为空时,禁用添加到喜欢的快捷键
Bug: https://pms.uniontech.com/bug-view-205103.html
> fix: 通过快捷键“.”将歌曲添加到“我喜欢的歌曲”，但歌单中未显示且喜欢图标未被标记

- src/music-player/mainFrame/mainframe.cpp
修复双击文件播放歌曲音乐不会置顶问题
Log: 修复双击文件播放歌曲音乐不会置顶问题
Bug: https://pms.uniontech.com/bug-view-206193.html
> fix: 双击文件播放音乐不会置顶

- src/music-player/core/vlc/MediaPlayer.cpp
- src/music-player/core/vlc/MediaPlayer.h
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlc/sdlplayer.h
修复播放音乐时未播放最后两秒，直接切换到下一首
Log: 修复播放音乐时未播放最后两秒，直接切换到下一首
Bug: https://pms.uniontech.com/bug-view-206605.html
> fix: 播放音乐未播放最后两秒，直接切换到下一首

- src/music-player/core/vlc/sdlplayer.cpp
修复休眠唤醒后进度条停滞，音乐无声音输出
Log: 修复休眠唤醒后进度条停滞，音乐无声音输出
Bug: https://pms.uniontech.com/bug-view-216759.html
> fix: 休眠唤醒后进度条停滞，音乐无声音输出

- src/music-player/ai/ai.cpp
- src/music-player/core/player.cpp
修复播放第一首歌曲导致崩溃问题；
修复播放权限为000文件卡死问题。
Log: 修复语音控制导致卡死/崩溃问题
Bug: https://pms.uniontech.com/bug-view-232273.html
https://pms.uniontech.com/bug-view-232289.html
> fix: 语音控制导致卡死/崩溃问题

- assets/deepin-music.json
- src/music-player/ai/ai.cpp
- src/music-player/mainFrame/footerwidget.cpp
- src/music-player/mainFrame/footerwidget.h
修复语音控制切换播放模式后tooltip内容与按钮不一致问题；修改配置文件播放控制参数为枚举
Log: 修复语音控制切换播放模式后tooltip内容与按钮不一致问题；
Bug: https://pms.uniontech.com/bug-view-232285.html
> fix: 语音控制-切换播放模式后tooltip内容与按钮不一致

- src/music-player/core/player.cpp
修复双击音频文件概率性无法自动播放、闪退问题
Log: 修复双击音频文件概率性无法自动播放、闪退问题
Bug: https://pms.uniontech.com/bug-view-232159.html
> fix: 双击音频文件概率性无法自动播放、闪退问题

- src/music-player/core/player.cpp
- src/music-player/core/playerbase.h
- src/music-player/core/qtplayer.cpp
- src/music-player/core/qtplayer.h
- src/music-player/core/vlc/MediaPlayer.cpp
- src/music-player/core/vlc/MediaPlayer.h
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlc/sdlplayer.h
- src/music-player/core/vlcplayer.cpp
- src/music-player/core/vlcplayer.h
修复双击音乐文件冷启动,显示播放，实际无音频输出问题
Log: 修复双击音乐文件冷启动,显示播放，实际无音频输出问题
Bug: https://pms.uniontech.com/bug-view-234211.html
> fix: 双击音乐文件冷启动,显示播放，实际无音频输出

- src/music-player/core/player.cpp
问题出现于音频恰好播放结束时拔出耳机孔，
此时界面处于暂停状态，但播放状态置为Eneded
此状被处理为 Invalid 状态，后续无法进入
播放流程。
修改将 Ended 也视为 Stopped 状态。
Log: 修复界面响应问题
Bug: https://pms.uniontech.com/bug-view-248763.html
> fix: 拔出耳机后，点击播放无响应

- assets/deepin-music.json
change the function call type name to the full name
Log: change the function call type name to the full name
Bug: https://pms.uniontech.com/bug-view-252383.html
> fix: change the function call type name to the full name

- src/music-player/core/player.cpp
- src/music-player/core/player.h
- src/music-player/mainFrame/footerwidget.cpp
- src/music-player/mainFrame/footerwidget.h
unpluging the headphones in the last 2s around gets low probability to not stop which let the icon dynamic
Log: In the above abnormal situation,let the icon static
Bug: https://pms.uniontech.com/bug-view-253209.html
> fix: the music keep playing while unpluging the headphones

- src/music-player/core/vlc/checkdatacaching.cpp
- src/music-player/core/vlc/checkdatacaching.h
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlc/sdlplayer.h
- src/music-player/core/vlcplayer.cpp
When the buffer is too large, the decoding is paused
Log: Fixed some known issues
> fix: Fixed the issue that the progress bar did not match

- src/music-player/musicbaseandsonglist/MusicBaselistview.qml
- src/music-player/musicbaseandsonglist/SideBarItem.qml
Fixed the issue that the scrollbar was blank
Bug: https://pms.uniontech.com/bug-view-273487.html
Log: Fixed the issue that the scrollbar was blank
> fix: Fixed the issue that the scrollbar was blank

- src/music-player/core/player.cpp
修复待机、休眠后继续音乐播放，放弃之前继续播放音乐逻辑
Bug: https://pms.uniontech.com/bug-view-277919.html
Log: 修复待机、休眠后继续音乐播放
> fix: 修复待机、休眠后继续音乐播放

- src/music-player/core/player.cpp
- src/music-player/core/player.h
修复锁屏后继续播放音乐
Bug: https://pms.uniontech.com/bug-view-277919.html
Log: 修复锁屏后继续播放音乐
> fix: 修复锁屏后继续播放音乐

- src/music-player/core/vlc/sdlplayer.cpp
修复音乐压测工具检测应用崩溃问题
Bug: https://pms.uniontech.com/bug-view-282191.html
Log: 修复音乐压测工具检测应用崩溃问题
> fix: 修复音乐压测工具检测应用崩溃问题

- src/music-player/dialogs/SettingsDialog.qml
- src/music-player/mainwindow/MainWindow.qml
[fix: can not open settings dialog](https://github.com/linuxdeepin/deepin-music/commit/5358cf925805b94169e2e452e93403d73c1e7865) 
As title, the string value can not access when set null.
Log: Fix can not open settings dialog.
Bug: https://pms.uniontech.com/bug-view-289833.html
Influence: UI
[fix: tray icon incorrect](https://github.com/linuxdeepin/deepin-music/commit/33f4a2711629d16f8800d7cbeb65e0ab37d6d9ca) 
the QIcon::fromTheme("", fallback) return fallback
if QIcon.availableSizes() is empty().
- DDciIconEngine not impl availableSizes()
We temporarily use icon.source, wait dtk fix it.
Log: fix tray icon.
Bug: https://pms.uniontech.com/bug-view-290021.html
> fix: setting dialogs and tray icon

- src/libdmusic/presenter.cpp
- src/music-player/musicList/AllMusicDefaultPage.qml
- src/music-player/musicmousemenu/ImportMenu.qml
[fix: custom playlist menu can not select](https://github.com/linuxdeepin/deepin-music/commit/9270751d3d169b7f73694436070a98c501d3b3c5) 
Use Menu manage MenuItem's layout, instead of Column.
Log: Fix custom playlist menu can not select
Bug: https://pms.uniontech.com/bug-view-292029.html
[fix: lost music info after close](https://github.com/linuxdeepin/deepin-music/commit/90f2500f2e26801192cc16030789cc806d5f3c24) 
We temporarily force exit in the previous changes,
lost save data to database.
Log: Fix lost music info after close.
Bug: https://pms.uniontech.com/bug-view-288439.html
[fix: import music not working](https://github.com/linuxdeepin/deepin-music/commit/de771278068fb3a35e237a4c27db4264ca97d5b9) 
Null not support on Qt6 QML, replace with empty list.
Log: Fix import music not …
> fix: menu and music info issue

- src/music-player/musicmousemenu/ImportMenu.qml
Use Instantiator replace Repeater, can manager
the order of MenuItems.
Log: Fix custom playlist order incorrect.
Bug: https://pms.uniontech.com/bug-view-292029.html
Influence: UI
> fix: custom playlist order is incorrect

- src/libdmusic/global.h
- src/libdmusic/util/utils.cpp
- src/music-player/mainwindow/Toolbar.qml
- src/music-player/musicList/AllMusicListView.qml
- src/music-player/musicmousemenu/ImportMenu.qml
- src/music-player/playlist/CurrentPlayList.qml
The select flag property can no longer be dynamiclly insert into the model item, we add it manually.
DTK api update, adjust background color.
Log: Fix select item no background color.
Bug: https://pms.uniontech.com/bug-view-290079.html
Influence: UI
> fix: select item no background color

- src/libdmusic/player/playerengine.cpp
- src/libdmusic/player/playerengine.h
- src/libdmusic/presenter.cpp
When playlist is empty, emit playPlaylistRequested signal to play all songs via MPRIS dbus interface.
Log: add playPlaylistRequested signal for empty playlist
Bug: https://pms.uniontech.com/bug-view-300607.html
> fix: add playPlaylistRequested signal for empty playlist

- src/music-player/musicbaseandsonglist/MusicBaselistview.qml
- src/music-player/musicmousemenu/SidebarMenu.qml
Update play menu item state based on playlist count to disable when empty
Log: update sidebar menu play button state
Bug: https://pms.uniontech.com/bug-view-290063.htm
> fix: update sidebar menu play button state

- src/libdmusic/core/dboperate.cpp
- src/music-player/mainwindow/MainWindow.qml
- Remove redundant import count check in DBOperate
- Update import failed dialog trigger condition
Log: optimize music import logic and dialog display
Bug: https://pms.uniontech.com/bug-view-289947.html
> fix: optimize music import logic and dialog display

- src/libdmusic/player/playerengine.cpp
Remove redundant playback status check before playing previous track
Log: simplify playPreMeta logic in playerengine
Bug: https://pms.uniontech.com/bug-view-290013.html
> fix: simplify playPreMeta logic in playerengine

- src/music-player/dialogs/EqualizerDialog.qml
Add maxVisibleItems property to improve ComboBox display in equalizer dialog
Log: limit equalizer preset dropdown items to 9
Bug: https://pms.uniontech.com/bug-view-300595.html
> fix: limit equalizer preset dropdown items to 9

- src/music-player/allItems/Shortcuts.qml
- src/music-player/mainwindow/GlobalVariant.qml
- src/music-player/mainwindow/WindowTitlebar.qml
- Add Ctrl+F shortcut to activate search box
- Add showSearchEdit signal in GlobalVariant
- Implement search box focus handling in WindowTitlebar
Log: add Ctrl+F shortcut for search function
Bug: https://pms.uniontech.com/bug-view-300877.htm
> fix: add Ctrl+F shortcut for search function

- src/music-player/mainwindow/MainWindow.qml
- src/music-player/mainwindow/MusicContentWindow.qml
- src/music-player/musicList/AllMusicList.qml
- src/music-player/musicList/AllMusicListView.qml
- src/music-player/util/eventsfilter.cpp
- Add Key_A to events filter
- Implement select all function in music list views
- Connect keyFiltered signal to handle Ctrl+A shortcut
- Only return true for space key to allow system shortcuts
Log: add Ctrl+A shortcut for select all in music list
Bug: https://pms.uniontech.com/bug-view-289885.htm
> fix: add Ctrl+A shortcut for select all in music list

- src/music-player/mainFrame/footerwidget.cpp
- src/music-player/mainFrame/footerwidget.h
Resolved an issue where the progress bar in deepin-music would: 
1.Turn gray upon clicking play
2.Jump to position 0
3.Then return to the previous playback position
Log: Correct progress bar initialization behavior
Bug: https://pms.uniontech.com/bug-view-325223.html
> fix: Fix progress bar initialization in music player
