- src/music-player/musicapp.cpp
> fix: should showNormal() when onRaise triggered

- music/music-player/view/lyricwidget.cpp
- music/music-player/view/widget/cover.cpp
- music/music-player/view/widget/delegate/musiclistdatadelegate.cpp
- music/music-player/view/widget/delegate/musicsearchlistdelegate.cpp
- music/music-player/view/widget/delegate/playitemdelegate.cpp
- music/music-player/view/widget/musicpixmapbutton.cpp
- music/music-player/view/widget/musictitleimage.cpp
- music/music-player/view/widget/soundvolume.cpp
- music/music-player/view/widget/tooltips.cpp
- music/music-player/view/widget/waveform.cpp
- music/music-player/view/widget/waveformscale.cpp
> fix: build failures under Qt 5.15

- music/libdmusic/CMakeLists.txt
- music/music-player/view/widget/soundpixmapbutton.cpp
don't install static file
Log:
> fix: don't install static file

- music/music-player/view/widget/soundpixmapbutton.cpp
Fixes build under Qt 5.15
Log: Fixes build under Qt 5.15
> fix: add missing QPainterPath include

- README.md
修改README里的依赖库说明
Log: 修改README里的依赖库说明
> fix: 修改README里的依赖库说明

- src/music-player/listView/musicInfoList/playlistview.cpp
待删除完所有歌曲后禁止播放歌曲
Log: 删除所有音乐过程中无法播发删除的音乐
Bug: https://pms.uniontech.com/bug-view-114973.html
> fix: 待删除完所有歌曲后仍在播放歌曲

- src/music-player/core/player.cpp
- src/music-player/core/player.h
- src/music-player/mainFrame/mainframe.cpp
- src/music-player/widget/soundvolume.cpp
- src/music-player/widget/soundvolume.h
调节音量时取消保存音量
Log: 调整音量正常
Bug: https://pms.uniontech.com/bug-view-113130.html
> fix: 部分机型调整音量会有卡顿的情况

- src/music-player/mainFrame/musiclistdatawidget.cpp
重新根据宽度计算显示范围
Log: 歌曲数目根据宽度刷新显示
> fix: 修改歌曲数目未根据宽度显示

- src/music-player/mainFrame/mainframe.cpp
- src/music-player/widget/soundvolume.cpp
设置音量大于1时自动取消静音
Log: 静音功能正常
Bug: https://pms.uniontech.com/bug-view-118041.html
> fix: 打开音量条静音后关闭音量条时会自动解除静音

- src/music-player/listView/musicInfoList/playlistview.cpp
播放列表添加时未验重
Log: 需要收藏歌曲正常
Bug: https://pms.uniontech.com/bug-view-118639.html
> fix: 我的收藏从文管添加重复歌曲时会在播放列表累计显示

- src/music-player/core/player.cpp
- src/music-player/core/player.h
- src/music-player/core/util/global.cpp
- src/music-player/core/vlc/MediaPlayer.cpp
- src/music-player/core/vlc/MediaPlayer.h
取消dbus设置音量
Log: 调整音量条不会卡顿
Bug: https://pms.uniontech.com/bug-view-113130.html
> fix: 通过dbus设置音量卡顿

- src/music-player/main.cpp
> fix: 调整音乐文件目录

- src/music-player/core/player.cpp
【性能】音乐冷启动速度变慢
Log: 【性能】音乐冷启动速度变慢
Bug: https://pms.uniontech.com/bug-view-121877.html
> fix: 【性能】音乐冷启动速度变慢

- src/music-player/core/player.cpp
- tests/testMain.cpp
> fix: 解决内存泄露

- tests/testQtMediaPlayer.cpp
> fix: 新增单元测试覆盖率

- src/libdmusic/metadetector.cpp
- src/music-player/core/vlcplayer.cpp
添加歌曲时可能会使音乐崩溃
Log: 添加歌曲时可能会使音乐崩溃
Bug: https://pms.uniontech.com/bug-view-122919.html
> fix: 添加歌曲时可能会使音乐崩溃

- src/music-player/mainFrame/musiclistdatawidget.cpp
- src/music-player/mainFrame/musiclistdatawidget.h
> fix: 音乐每次启动的时候所有音乐均显示为15首歌曲

- src/music-player/core/player.cpp
- src/music-player/core/vlc/Media.cpp
- src/music-player/core/vlc/Media.h
暂停时未将歌曲设置到播放器
Log: 播放演唱者或专辑歌曲正常
> fix: 演唱者或专辑页面详情页面播放任意歌曲后暂停然后删除歌曲后继续播放的歌曲为删除掉的歌曲

- src/music-player/core/vlc/Instance.cpp
> fix: 内存泄露调整

- src/music-player/mainFrame/mainframe.cpp
> fix: 在文官中打开歌曲后无法触发均衡器效果

- src/music-player/core/vlc/Instance.cpp
> fix: 调整代码，解决内存泄露

- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
- tests/testApplication.cpp
窗口显示状态错误
Log: 托盘正常唤起音乐
Bug: https://pms.uniontech.com/bug-view-124509.html
> fix: 托盘音乐图标点击多次后无法唤起音乐窗口

- src/music-player/core/util/global.cpp
- src/music-player/core/util/global.h
- src/music-player/main.cpp
- src/music-player/mainFrame/footerwidget.cpp
- src/music-player/mainFrame/footerwidget.h
添加音乐应用播放音频过程中系统阻止锁屏/待机
Log: 音乐应用播放音频过程中系统阻止锁屏/待机
Bug: https://pms.uniontech.com/bug-view-124839.html
> fix: 音乐应用播放音频过程中系统会自动锁屏/待机

- src/music-player/core/player.cpp
- src/music-player/core/qtplayer.cpp
- src/music-player/core/qtplayer.h
暂停后静音，再继续播放时音乐会出一秒左右的声音
Log: 暂停后静音，再继续播放时音乐会出一秒左右的声音
Bug: https://pms.uniontech.com/bug-view-127405.html
> fix: 暂停后静音，再继续播放时音乐会出一秒左右的声音

- src/music-player/core/qtplayer.cpp
调整下一首设置
Log: 调整下一首设置
Bug: https://pms.uniontech.com/bug-view-129869.html
> fix: 调整下一首设置

- src/music-player/core/util/global.cpp
- src/music-player/main.cpp
> fix: 添加类型判断

- src/music-player/core/util/global.cpp
> fix: 添加一个类型

- debian/control
> chore: 去除多余的安装依赖库

- src/music-player/listView/musicBaseAndSongList/musicbaseandsonglistmodel.cpp
- src/music-player/listView/musicBaseAndSongList/musicbaselistview.cpp
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
- src/music-player/listView/musicInfoList/playlistmodel.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
修改了音乐拖拽时鼠标指针样式问题
Log: 音乐拖拽时鼠标指针样式正确显示
Bug: https://pms.uniontech.com/bug-view-112585.html
> fix: 音乐拖拽时鼠标指针样式问题

- README.md
- debian/control
- src/music-player/listView/musicBaseAndSongList/musicbaseandsonglistmodel.cpp
- src/music-player/listView/musicBaseAndSongList/musicbaselistview.cpp
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
- src/music-player/listView/musicInfoList/playlistmodel.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
添加推荐gstreamer依赖，修改音乐拖拽时鼠标指针样式问题，修改 deepin-music / README中的无效链接
Log: no
> fix:  gstreamer播放音乐没有声音、音乐拖拽时鼠标指针样式问题、Update README.md

- src/music-player/presenter/databaseservice.h
> chore: 初始化歌单结构

- src/music-player/core/player.cpp
- src/music-player/core/util/musiclyric.cpp
- src/music-player/core/vlc/Media.cpp
- src/music-player/core/vlc/cda.cpp
修复cppcheck检查错误
Log: 修复cppcheck检查错误
> fix: 修复cppcheck检查错误

- debian/changelog
- src/music-player/CMakeLists.txt
- src/music-player/core/player.cpp
- src/music-player/core/util/eventlogutils.cpp
- src/music-player/core/util/eventlogutils.h
- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/mainFrame/mainframe.cpp
> feat: 添加数据埋点内容

- debian/changelog
- src/music-player/mainFrame/musiclistdatawidget.cpp
修复在专辑艺人页面导入歌曲，专辑、艺人数未刷新问题
Log: 修复已知bug
> fix: 修复在专辑艺人页面导入歌曲，专辑、艺人数未刷新问题

- src/music-player/core/player.cpp
- src/music-player/core/util/eventlogutils.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/mainFrame/mainframe.cpp
> fix: 数据埋点 添加应用版本号

- tests/CMakeLists.txt
修复单元测试编译失败问题
Bug: https://pms.uniontech.com/bug-view-148721.html
Log: no
> fix: 修复单元测试编译失败问题

- src/music-player/core/player.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/mainFrame/mainframe.cpp
暂时屏蔽除启动外的数据埋点
Log: 屏蔽除启动外的数据埋点
> fix: 屏蔽部分数据埋点

- src/music-player/core/player.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/mainFrame/mainframe.cpp
Reverts linuxdeepin/deepin-music#327
> Revert "fix: 屏蔽部分数据埋点"

- src/music-player/listView/musicBaseAndSongList/musicbaselistview.cpp
- src/music-player/listView/musicBaseAndSongList/musicbaselistview.h
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.h
- src/music-player/mainFrame/musiclistscrollarea.cpp
同步歌单样式
Log: 歌单样式一致
Bug: https://pms.uniontech.com/bug-view-155745.html
/review @lzwind @myk1343 @hundundadi @feeengli
> fix: 深色模式下窗口未激活侧边栏的显示问题

- src/music-player/mainFrame/addmusicwidget.cpp
- src/music-player/mainFrame/addmusicwidget.h
更新添加音乐按钮控件
Log: 更新添加音乐按钮控件
Bug: https://pms.uniontech.com/bug-view-155749.html
/review @lzwind @myk1343 @feeengli @hundundadi
> fix: 添加音乐按钮控件需要更新

- src/music-player/mainFrame/subsonglistwidget.cpp
深色模式下专辑背景页歌曲名匹配深色状态
Log: 深色模式下专辑背景页显示正常
Bug: https://pms.uniontech.com/bug-view-155757.html
/review @lzwind @myk1343 @hundundadi @feeengli
> fix: 深色模式下专辑背景页歌曲名未匹配深色状态

- debian/rules
> fix: debian build

- debian/control
- src/music-player/core/player.cpp
- src/music-player/core/vlc/MediaPlayer.h
- src/music-player/core/vlc/checkdatazerothread.cpp
- src/music-player/core/vlc/checkdatazerothread.h
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlc/sdlplayer.h
- src/music-player/core/vlc/vlcdynamicinstance.cpp
- src/music-player/core/vlc/vlcdynamicinstance.h
- src/music-player/core/vlcplayer.cpp
添加sdl播放器
Log: 添加sdl播放器
Bug: https://pms.uniontech.com/task-view-196661.html
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi
> feat: 添加sdl播放器

- src/music-player/core/vlc/vlcdynamicinstance.cpp
修改动态加载库获取路径
Log: 修改动态加载库获取路径
/review @lzwind @myk1343 @feeengli @jeffshuai @pengfeixx @HeeMingYang @hundundadi
> fix: 修改动态加载库获取路径

- src/music-player/mainFrame/musiclistdatawidget.cpp
修复歌单html标签显示异常问题
Log: 修复歌单html标签显示异常问题
Bug: https://pms.uniontech.com/bug-view-163857.html
> fix: 修复歌单html标签显示异常问题

- src/libmusic-plugin/voiceplugin.cpp
- src/music-player/main.cpp
- src/music-player/speech/speechCenter.cpp
- src/music-player/speech/speechCenter.h
语音助手添加快进快退功能
Log: 语音助手添加快进快退功能
> feat: 语音助手添加快进快退功能

- src/music-player/mainFrame/mainframe.cpp
添加 WindowTitle
Log: 应用获取打开文件路径
Task: https://pms.uniontech.com/task-view-218113.html
> fix: 应用获取打开文件路径

- src/music-player/core/vlc/sdlplayer.cpp
所有平台都使用sdl播放器
Log: 修复点击进度条会有轻微的POP音问题
Bug: https://pms.uniontech.com/bug-view-175947.html
> fix: 点击进度条会有轻微的POP音

- debian/changelog
- linglong.yaml
- src/music-player/CMakeLists.txt
- src/music-player/allItems/ImageCell.qml
- src/music-player/mainwindow/Toolbar.qml
同步V23代码、更新版本号
Log: 同步V23代码、更新版本号
> fix: 同步V23代码、更新版本号

- .tx/deepin.conf
- debian/changelog
New version 6.2.24
Log: new version 6.2.24
> feat: new version 6.2.24

- .tx/deepin.conf
> fix: 修改翻译分支

- src/music-player/CMakeLists.txt
- src/music-player/musicList/AllMusicListDelegate.qml
- src/music-player/musicmousemenu/ImportMenu.qml
- src/music-player/musicmousemenu/MusicMoreMenu.qml
- src/music-player/musicsublist/AlbumSublistDelegate.qml
- src/music-player/musicsublist/ArtistSublistDelegate.qml
- src/music-player/playlist/CurrentPlayListDelegate.qml
添加边框；右键菜单显示时悬浮按钮不隐藏
Log: 添加边框；右键菜单显示时悬浮按钮不隐藏
Bug: https://pms.uniontech.com/bug-view-168469.html
https://pms.uniontech.com/bug-view-168401.html
> fix: 添加边框；右键菜单显示时悬浮按钮不隐藏

- src/music-player/dialogs/CloseConfirmDialog.qml
- src/music-player/mainwindow/MainWindow.qml
- src/music-player/mainwindow/Toolbar.qml
- src/music-player/playlist/CurrentPlayList.qml
关闭提示窗口bug修复
Log: 关闭提示窗口bug修复
Bug: [pms.uniontech.com/bug-view-179189.html](https://pms.uniontech.com/bug-view-179189.html)
> fix: 关闭提示窗口bug修复

- src/music-player/dialogs/CloseConfirmDialog.qml
- translations/deepin-music_en.ts
- translations/deepin-music_zh_CN.ts
- translations/deepin-music_zh_HK.ts
- translations/deepin-music_zh_TW.ts
修复关闭提示窗口无法选择bug
Log: 修复关闭提示窗口无法选择bug
> fix: 修复关闭提示窗口无法选择bug

- src/music-player/dialogs/MusicInfoDialog.qml
- src/music-player/dialogs/PropertyItemDelegate.qml
- src/music-player/musicList/AllMusicDefaultPage.qml
- src/music-player/musicbaseandsonglist/CustomPlaylistModel.qml
- src/music-player/musicmousemenu/ImportMenu.qml
- src/music-player/toolbar/StripedRectangle.qml
- src/music-player/toolbar/WaveformRect.qml
- translations/deepin-music_en.ts
- translations/deepin-music_zh_CN.ts
右键菜单排序、进度条、缺省页bug修复
Log: 右键菜单排序、进度条、缺省页bug修复
Bug: https://pms.uniontech.com/bug-view-177301.html
https://pms.uniontech.com/bug-view-176575.html
https://pms.uniontech.com/bug-view-168521.html
> fix: 右键菜单排序、进度条、缺省页bug修复

- src/music-player/musicbaseandsonglist/CustomPlaylistModel.qml
- src/music-player/toolbar/WaveformRect.qml
限制进度条滑块显示范围，防止超出进度条区域
Log: 限制进度条滑块显示范围，防止超出进度条区域
> fix: 限制进度条滑块显示范围

- src/music-player/dialogs/DeleteSonglistDialog.qml
- src/music-player/lyric/EffectSun.qml
- src/music-player/lyric/LyricPage.qml
- src/music-player/lyric/ShaderView.qml
- src/music-player/lyric/effectpublic/CusShaderToy.qml
- src/music-player/playlist/CurrentPlayList.qml
- src/music-player/playlist/CurrentPlayListDelegate.qml
- src/music-player/toolbar/WaveformRect.qml
播放列表添加拖拽滚动功能，删除歌曲提示窗口显示问题修复
Log: 播放列表添加拖拽滚动功能，删除歌曲提示窗口显示问题修复
Bug: https://pms.uniontech.com/bug-view-165957.html
https://pms.uniontech.com/bug-view-185583.html
> fix: 播放列表拖拽滚动

- src/music-player/dialogs/DeleteSonglistDialog.qml
- src/music-player/dialogs/PropertyItemDelegate.qml
删除提示窗口显示不全问题修复
Log: 删除提示窗口显示不全问题修复
Bug: https://pms.uniontech.com/bug-view-185583.html
> fix: 删除提示窗口显示不全问题

- src/music-player/mainwindow/MainWindow.qml
- src/music-player/mainwindow/MusicContentWindow.qml
- src/music-player/musicbaseandsonglist/MusicBaselistview.qml
UI bug修复
Log: UI bug修复
Bug: https://pms.uniontech.com/bug-view-168351.html
> fix: UI bug修复

- debian/control
- linglong.yaml
- src/libdmusic/player/vlc/MediaPlayer.h
- src/libdmusic/player/vlc/checkdatazerothread.cpp
- src/libdmusic/player/vlc/checkdatazerothread.h
- src/libdmusic/player/vlc/sdlplayer.cpp
- src/libdmusic/player/vlc/sdlplayer.h
- src/libdmusic/player/vlc/vlcdynamicinstance.cpp
- src/libdmusic/player/vlc/vlcdynamicinstance.h
- src/libdmusic/player/vlcplayer.cpp
- src/libdmusic/player/vlcplayer.h
- src/music-player/mainwindow/MainWindow.qml
- src/music-player/toolbar/VolumeSlider.qml
添加sdl播放器
Log: 添加sdl播放器
Bug: https://pms.uniontech.com/bug-view-174257.html
> fix: 添加sdl播放器

- debian/rules
- src/CMakeLists.txt
- src/libmusic-plugin/CMakeLists.txt
- src/music-player/CMakeLists.txt
代替 https://github.com/linuxdeepin/deepin-music/pull/333
> chore: use GNUInstallDirs in CmakeLists

- src/music-player/listView/musicInfoList/playlistview.cpp
修复屏幕缩放不为1时拖拽图标锯齿问题
Log: 修复屏幕缩放不为1时拖拽图标锯齿问题
Bug: https://pms.uniontech.com/bug-view-155783.html
> fix: 拖拽图标锯齿问题

- linglong.yaml
> fix: 玲珑打包问题修复

- src/music-player/core/player.cpp
- src/music-player/core/playerbase.h
- src/music-player/core/qtplayer.cpp
- src/music-player/core/qtplayer.h
- src/music-player/core/util/global.cpp
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlcplayer.cpp
- src/music-player/core/vlcplayer.h
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
修复klv/klu蓝牙耳机暂停后无法播放问题
Log: 修复klv/klu蓝牙耳机暂停后无法播放问题
Bug: https://pms.uniontech.com/bug-view-187869.html
https://pms.uniontech.com/bug-view-181325.html
> fix: klv蓝牙耳机双击不播放问题

- src/music-player/core/player.cpp
修复设置音量为0后播放下一首歌曲无法恢复音量问题
Log: 修复设置音量为0后播放下一首歌曲无法恢复音量问题
Bug: https://pms.uniontech.com/bug-view-190837.html
> fix: 设置音量为0后播放下一首无法恢复音量问题

- src/libdmusic/global.cpp
- src/music-player/lyric/EffectLightWave.qml
- src/music-player/lyric/EffectLine.qml
- src/music-player/lyric/EffectParticle.qml
- src/music-player/lyric/EffectRing.qml
- src/music-player/lyric/EffectSun.qml
- src/music-player/lyric/EffectWaterWave.qml
- src/music-player/mainwindow/GlobalVariant.qml
- src/music-player/mainwindow/MainWindow.qml
- src/music-player/musicList/AllMusicListDelegate.qml
> fix: 调整动效、添加日志

- debian/changelog
New tag number 6.2.25
Log: new tag number 6.2.25
> chore: new tag number 6.2.25

- patches/fix-library-path.patch
未同步修改patch导致玲珑打包失败
Log: 未同步修改patch导致玲珑打包失败
> fix: 玲珑打包问题

- debian/changelog
New tag number 6.2.26
Log: new tag number 6.2.26
> chore: new tag number 6.2.26

- src/music-player/core/vlc/sdlplayer.cpp
pgw播放卡顿问题修复
Log: pgw播放卡顿问题修复
Bug: https://pms.uniontech.com/bug-view-191699.html
> fix: pgw播放卡顿问题修复

- src/music-player/CMakeLists.txt
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlc/sdlplayer.h
修复pgw切换下一曲时声音从显示器输出问题
Log: 修复pgw切换下一曲时声音从显示器输出问题
Bug: https://pms.uniontech.com/bug-view-194025.html
> fix: pgw声音从HDMI输出

- src/music-player/CMakeLists.txt
修复其它架构编译失败问题
Log: 修复其它架构编译失败问题
> fix: 修复其它架构编译失败问题

- debian/changelog
New version 6.2.27
Log: new version 6.2.27
> chore: new version 6.2.27

- src/music-player/core/util/global.cpp
> fix: 增加hw新机型判断

- src/music-player/dialogs/SettingsDialog.qml
修复设置界面背景颜色问题
Log: 修复设置界面背景颜色问题
Bug: https://pms.uniontech.com/bug-view-198891.html
> fix: 设置界面背景颜色不随主题变化

- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
- src/music-player/mainFrame/musiclistdatawidget.cpp
- src/music-player/mainFrame/musiclistscrollarea.cpp
修复紧凑模式标题栏按钮位置错位问题，切换字体后部分内容未刷新问题
Log: 修复紧凑模式标题栏按钮位置错位问题，切换字体后部分内容未刷新问题
Bug: https://pms.uniontech.com/bug-view-202829.html
https://pms.uniontech.com/bug-view-202091.html
> fix: 紧凑模式显示问题，字体切换问题

- src/CMakeLists.txt
- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
1050 dtk不支持紧凑模式
Log: 修复1050 dtk不支持紧凑模式
> fix: 紧凑模式1050适配

- src/CMakeLists.txt
- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
紧凑模式兼容，通过DTK宏判断
Log: 紧凑模式兼容，通过DTK宏判断
> fix: 紧凑模式兼容，通过DTK宏判断

- debian/changelog
New tag 6.2.28
Log: new tag 6.2.28
> chore: new tag 6.2.28

- src/music-player/core/util/global.cpp
- src/music-player/core/util/global.h
- src/music-player/mainFrame/footerwidget.cpp
添加m900判断，并在播放时阻止锁屏
Log: 添加m900判断，并在播放时阻止锁屏
Bug: https://pms.uniontech.com/bug-view-204439.html
> fix: m900无法阻止锁屏

- src/music-player/core/util/global.cpp
修复阻止锁屏失败问题
Log: 修复阻止锁屏失败问题
Bug: https://pms.uniontech.com/bug-view-204439.html
> fix: 阻止锁屏失败

- src/music-player/core/util/global.cpp
> fix: 新增pgw判断

- src/music-player/mainwindow/MainWindow.qml
修改左侧sidebar透明度
Log: 修改左侧sidebar透明度
Bug: https://pms.uniontech.com/bug-view-168351.html
> fix: 修改左侧sidebar透明度

- assets/org.deepin.music.json
- src/music-player/CMakeLists.txt
- src/music-player/core/util/global.cpp
Description: hw机型判断适配dconfig
Log: hw机型判断适配dconfig
Task: https://pms.uniontech.com/task-view-276433.html
> feat: hw机型判断适配dconfig

- debian/changelog
> chore: new tag 6.2.29

- debian/changelog
New tag 6.2.30
Log: new tag 6.2.30
> chore: new tag 6.2.30

- src/music-player/core/vlc/sdlplayer.cpp
修复pa连接失败时播放音乐崩溃问题
Log: 修复pa连接失败时播放音乐崩溃问题
> fix: pa连接失败时播放音乐崩溃

- debian/changelog
New tag 6.2.31
Log: new tag 6.2.31
> chore: new tag 6.2.31

- src/music-player/main.cpp
修复强制退出不保存导入的歌曲
Log: 修复强制退出不保存导入的歌曲\
Bug: https://pms.uniontech.com/bug-view-215039.html
> fix: 强制退出不保存导入的歌曲

- debian/changelog
New tag 7.0.3
Log: new tag 7.0.3
> chore: new tag 7.0.3

- debian/changelog
> chore: tag 6.2.32

- debian/changelog
> chore: tag 6.2.33

- src/music-player/listView/musicBaseAndSongList/musicsonglistview.cpp
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.h
- src/music-player/listView/singerList/singerlistview.cpp
部分dtk新增接口未进行判断
Log: 修复1042编译失败问题
> fix: 1042编译失败

- debian/changelog
> chore: tag 6.2.34

- assets/deepin-music.json
- src/music-player/ai/ai.cpp
调整function为5个
Log: 调整function为5个
> fix: 调整function为5个

- assets/deepin-music.json
- src/music-player/ai/ai.cpp
- src/music-player/speech/speechCenter.cpp
修复修复语音控制播放顺序不一致、播放000权限文件后无法进行其它操作问题
Log: 修复修复语音控制播放顺序不一致、播放000权限文件后无法进行其它操作问题
Bug: https://pms.uniontech.com/bug-view-232289.html
https://pms.uniontech.com/bug-view-232303.html
https://pms.uniontech.com/bug-view-232655.html
> fix: 语音控制播放顺序不一致，播放000权限文件后无法进行其它操作

- assets/deepin-music.json
修复输入播放第几首歌时部分中文索引会减一问题
Log: 修复输入播放第几首歌时部分中文索引会减一问题
Bug: https://pms.uniontech.com/bug-view-232303.html
> fix: 输入播放第几首歌时部分中文索引会减一

- debian/changelog
> chore: tag 6.2.35

- debian/changelog
> chore: tag 6.2.36

- src/music-player/core/util/global.cpp
adapt to new models
Log: adapt to new models
> feat: adapt to new models

- debian/changelog
> chore: tag 6.2.37

- src/music-player/CMakeLists.txt
resubmit: fix: don't set RPATH #423
Log: remove unnecessary properties
> fix: remove unnecessary properties

- src/music-player/listView/albumList/albumdelegate.cpp
- src/music-player/listView/albumList/albumlistview.cpp
- src/music-player/listView/albumList/albumlistview.h
- src/music-player/listView/musicBaseAndSongList/musicbaselistview.h
- src/music-player/listView/musicBaseAndSongList/musicsonglistview.h
- src/music-player/listView/musicInfoList/playitemdelegate.cpp
- src/music-player/listView/musicInfoList/playlistview.cpp
- src/music-player/listView/musicInfoList/playlistview.h
- src/music-player/listView/musicSearchList/musicsearchlistview.cpp
- src/music-player/listView/singerList/singerdelegate.cpp
- src/music-player/listView/singerList/singerlistview.cpp
- src/music-player/listView/singerList/singerlistview.h
- src/music-player/main.cpp
- src/music-player/mainFrame/addmusicwidget.cpp
- src/music-player/mainFrame/footerwidget.h
- src/music-player/mainFrame/mainframe.h
- src/music-player/mainFrame/musiccontentwidget.h
- src/music-player/mainFrame/musiclistdatawidget.cpp
- src/music-player/mainFrame/musiclistdatawidget.h
- src/music-player/mainFrame/musiclistscrollarea.h
- src/music-player/mainFrame/subsonglistwidget.h
- src/music-player/tablet/tabletlabel.cpp
- src/music-player/widget/ddropdown.h
- src/music-player/widget/infodialog.cpp
- src/music-player/widget/lrc/lyriclabel.cpp
- src/music-player/widget/playqueuewidget.h
Fix V23 environment build failure issue
Log: fix V23 environment build failure issue
> fix: failed to build in V23 environment

- debian/changelog
> chore: tag 6.2.38

- src/music-player/mainwindow/MainWindow.qml
> fix: The tray icon does not change with the theme

- src/music-player/mainFrame/mainframe.cpp
修复连续点击托盘图标不能打开和关闭窗口
Log: 修复连续点击托盘图标不能打开和关闭窗口
Bug: https://pms.uniontech.com/bug-view-241657.html
> fix: 连续点击托盘图标不能打开和关闭窗口

- debian/changelog
> chore: tag 6.2.39

- debian/changelog
> chore: bump version to 7.0.4

- debian/changelog
> chore: bump version to 7.0.5

- src/music-player/core/vlc/MediaPlayer.cpp
- src/music-player/core/vlc/checkdatacaching.cpp
- src/music-player/core/vlc/sdlplayer.cpp
Fixed the playback status inconsistency
Log: Fixed some known issues
> fix: Fixed the playback status inconsistency

- src/music-player/musicbaseandsonglist/SideBarItem.qml
Adjust the small font size of the sidebar to the appropriate size.
Log: sidebar font size
Bug: https://pms.uniontech.com/bug-view-264051.html
> fix: sidebar font size

- src/music-player/musicList/AllMusicListDelegate.qml
- src/music-player/musicsublist/AlbumSublistDelegate.qml
- src/music-player/musicsublist/ArtistSublistDelegate.qml
- src/music-player/playlist/CurrentPlayListDelegate.qml
The status of the favorite button is incorrect
Bug: https://pms.uniontech.com/bug-view-264151.html
Log: The status of the favorite button is incorrect
> fix: The status of the favorite button is incorrect

- src/music-player/musicList/AllMusicListDelegate.qml
- src/music-player/musicsublist/AlbumSublistDelegate.qml
- src/music-player/musicsublist/ArtistSublistDelegate.qml
- src/music-player/toolbar/VolumeSlider.qml
Bug: https://pms.uniontech.com/bug-view-181343.html
Bug: https://pms.uniontech.com/bug-view-169101.html
> fix: Fixed some bugs

- src/music-player/dialogs/MusicInfoDialog.qml
- src/music-player/dialogs/PropertyItemDelegate.qml
Fixed the information dialog issue
Bug: https://pms.uniontech.com/bug-view-169131.html
Log: Fixed the information dialog issue
> fix: Fixed the information dialog issue

- src/music-player/albumlist/AlbumGridDelegate.qml
- src/music-player/albumlist/AlbumListDelegate.qml
- src/music-player/allItems/ImageCell.qml
- src/music-player/allItems/ToolButtonItem.qml
- src/music-player/mainwindow/Toolbar.qml
- src/music-player/singerlist/ArtistGridDelegate.qml
Fixed the color of list items
Bug: https://pms.uniontech.com/bug-view-181343.html
Log: Fixed the color of list items
Fixed the issue of button hovering
Bug: https://pms.uniontech.com/bug-view-264127.html
Log: Fixed the issue of button hovering
Fix toolbar border error
Bug: https://pms.uniontech.com/bug-view-169131.html
Log: Fix toolbar border error
> Fixed the color of list items

- src/music-player/core/vlcplayer.cpp
修复SW节能模式下播放卡顿
Bug: https://pms.uniontech.com/bug-view-264293.html
Log: 修复SW节能模式下播放卡顿
> fix: 修复SW节能模式下播放卡顿

- src/music-player/lyric/LyricRect.qml
- src/music-player/mainwindow/Toolbar.qml
- src/music-player/musicList/AllMusicListDelegate.qml
- src/music-player/singerlist/ArtistGridDelegate.qml
Fixed an issue with the artist thumbnail playing icon
Bug: https://pms.uniontech.com/bug-view-264127.html
Log: Fixed an issue with the artist thumbnail playing icon
Sync v20 volume bar to hide time
Bug: https://pms.uniontech.com/bug-view-215775.html
Log: Sync v20 volume bar to hide time
Fixed lyrics scrolling issue
Bug: https://pms.uniontech.com/bug-view-234233.html
Log: Fixed lyrics scrolling issue
> Fixed an issue with the artist thumbnail playing icon

- src/music-player/mainwindow/WindowTitlebar.qml
- src/music-player/musicsublist/AlbumSublistDelegate.qml
- src/music-player/musicsublist/ArtistSublistDelegate.qml
- src/music-player/playlist/CurrentPlayListDelegate.qml
Fixed about interface exceptions
Bug: https://pms.uniontech.com/bug-view-241077.html
Log: Fixed about interface exceptions
Fixed the abnormal status of the selected icon in the list
Bug: https://pms.uniontech.com/bug-view-168469.html
Log: Fixed the abnormal status of the selected icon in the list
The issue that the tip is not displayed is fixed
Bug: https://pms.uniontech.com/bug-view-169843.html
log: The issue that the tip is not displayed is fixed
> Fixed about interface exceptions

- src/libdmusic/core/datamanager.cpp
- src/music-player/dialogs/EqualizerDialog.qml
- src/music-player/dialogs/MusicInfoDialog.qml
- src/music-player/toolbar/StripedRectangle.qml
- src/music-player/toolbar/WaveformItem.qml
- src/music-player/toolbar/WaveformRect.qml
Fixed the color issue of the volume bar
Bug: https://pms.uniontech.com/bug-view-169857.html
Log: Fixed the color issue of the volume bar
> fix: Fixed the color issue of the volume bar

- src/libdmusic/global.cpp
- src/libdmusic/global.h
- src/music-player/main.cpp
music treeland adaptation
Log: music treeland adaptation
> fix: music treeland adaptation

- src/music-player/dialogs/CDRemovedDialog.qml
- src/music-player/dialogs/CloseConfirmDialog.qml
- src/music-player/dialogs/DeleteLocalDialog.qml
- src/music-player/dialogs/DeleteSonglistDialog.qml
- src/music-player/dialogs/EqualizerDialog.qml
- src/music-player/dialogs/MusicInfoDialog.qml
- src/music-player/dialogs/SettingsDialog.qml
- src/music-player/mainwindow/MusicContentWindow.qml
- src/music-player/mainwindow/SearchResultWindow.qml
- src/music-player/mainwindow/WindowTitlebar.qml
Fix the search results screen
Bug: https://pms.uniontech.com/bug-view-270183.html
Log: Fix the search results screen
Fixed the title bar exception
Bug: https://pms.uniontech.com/bug-view-269999.html
https://pms.uniontech.com/bug-view-269997.html
Log: Fixed the title bar exception
> Fix the search results screen

- src/music-player/core/vlc/MediaPlayer.cpp
- src/music-player/core/vlc/MediaPlayer.h
- src/music-player/core/vlc/sdlplayer.cpp
修复ogg快进快退进度显示问题
Bug: https://pms.uniontech.com/bug-view-274213.html
Log: 修复ogg快进快退进度显示问题
> fix: 修复ogg快进快退进度显示问题

- src/music-player/dialogs/SettingsDialog.qml
Fixed the issue of the settings window
Log: Fixed the issue of the settings window
> fix: Fixed the issue of the settings window

- src/libdmusic/metadetector.cpp
- src/libdmusic/metadetector.h
- src/music-player/core/vlc/sdlplayer.cpp
- src/music-player/core/vlcplayer.cpp
修复ape格式多次暂停播放无声问题
Bug: https://pms.uniontech.com/bug-view-275987.html
Log: 修复ape格式多次暂停播放无声问题
> fix: 修复ape格式多次暂停播放无声问题

- src/music-player/core/player.cpp
- src/music-player/core/vlcplayer.cpp
- src/music-player/core/vlcplayer.h
使用qt播放器播放ape文件
Bug: https://pms.uniontech.com/bug-view-275987.html
Log: 使用qt播放器播放ape文件
Change-Id: I36e146d99737c5b411e494b7fb0d25db8c7e2dd4
> fix: 使用qt播放器播放ape文件

- debian/control
Supplement libmpris dependency
Log: Supplement libmpris dependency
> fix: Supplement libmpris dependency

- src/music-player/mainFrame/importwidget.cpp
- src/music-player/mainFrame/importwidget.h
- src/music-player/mainFrame/mainframe.cpp
- src/music-player/mainFrame/mainframe.h
修复删除歌单后最小化托盘再加载音乐显示问题
Bug: https://pms.uniontech.com/bug-view-280819.html
Log: 修复删除歌单后最小化托盘再加载音乐显示问题
> fix: 修复删除歌单后最小化托盘再加载音乐显示问题

- debian/changelog
- src/libdmusic/global.cpp
- src/libdmusic/global.h
- src/music-player/main.cpp
remove kwayland-shell env
Log: remove kwayland-shell env
> fix: remove kwayland-shell env

- debian/control
Supplement SDL dependency
Log: Supplement SDL dependency
> fix: Supplement SDL dependency

- src/libdmusic/core/audioanalysis.cpp
Fix the issue of importing abnormal files
Bug: https://pms.uniontech.com/bug-view-281257.html
Log: Fix the issue of importing abnormal files
> fix: Fix the issue of importing abnormal files

- src/libdmusic/player/vlc/sdlplayer.cpp
Fixed the next song being stuck playing under Treeland
Bug: https://pms.uniontech.com/bug-view-286297.html
Log: Fixed the next song being stuck playing under Treeland
> fix: Fixed the next song being stuck playing under Treeland

- src/music-player/deepin-music.qrc
- src/music-player/lyric/ShaderView.qml
- src/music-player/playlist/CurrentFloatingPanel.qml
- src/music-player/playlist/CurrentPlayList.qml
[fix: Modify the playlist background]
Modify the playlist background
Log: Modify the playlist background
[fix: Remove the point effect]
Remove the point effect
Bug: https://pms.uniontech.com/bug-view-269055.html
Log: Remove the point effect
> fix: Modify the playlist background

- src/music-player/playlist/CurrentPlayList.qml
Remove playlist slide effect
Bug: https://pms.uniontech.com/story-view-36405.html
Log: Remove playlist slide effect
> fix: Remove playlist slide effect

- debian/control
Remove development dependencies
Log: Remove development dependencies
> fix: Remove development dependencies

- debian/changelog
Update changelog
Log: Update changelog
> chaore: Update changelog

- README.md
- README.zh_CN.md
- debian/control
> fix: remove unused dframeworkdbus dep

- src/libdmusic/presenter.cpp
- src/libdmusic/presenter.h
- src/music-player/dialogs/CloseConfirmDialog.qml
Fix the issue of new process starting when exiting
Log: Fix the issue of new process starting when exiting
> fix: Fix the issue of new process starting when exiting

- src/music-player/mainwindow/WindowTitlebar.qml
- src/music-player/musicbaseandsonglist/MusicBaselistview.qml
- src/music-player/musicbaseandsonglist/SideBarItem.qml
[fix: titlebar layout](https://github.com/linuxdeepin/deepin-music/commit/bc89bff131ee525acf75c9bec443caf513db3319) 
Adjust titlebar layout.
Log: Adjust titlebar layout.
Bug: https://pms.uniontech.com/bug-view-289505.html
Influence: UI
[fix: sidebar background color](https://github.com/linuxdeepin/deepin-music/commit/7c4fe8cb16ebe9c77984928dcfbe6a6118ef343e) 
DTK api update, adjust sidebar background color.
Log: Adjust sidebar background color.
Bug: https://pms.uniontech.com/bug-view-289767.html
Influence: UI
> fix: adjust titlebar layout and sidebar background color

- src/libdmusic/presenter.cpp
- src/music-player/mainwindow/MainWindow.qml
Fixed the issue that settings were not saved when exiting
Log: Fixed the issue that settings were not saved when exiting
> fix: Fixed the issue that settings were not saved when exiting

- src/music-player/core/vlc/sdlplayer.cpp
remove invalid  url
Log: remove invalid  url
> fix: remove invalid  url

- arm64/linglong.yaml
- debian/changelog
- deploy_dep
- install_dep
- linglong.yaml
- loong64/linglong.yaml
Add linglong manifests.
Log: Adapt linglong.
> chore: Adapt linglong

- src/libdmusic/player/qtplayer.cpp
- src/libdmusic/player/vlc/sdlplayer.cpp
update dbus name
Log: update dbus name
> fix: update dbus name

- arm64/linglong.yaml
- linglong.yaml
- loong64/linglong.yaml
update linglong version
Log:update linglong version
> chore: update linglong version

- src/music-player/allItems/ToolButtonItem.qml
- src/music-player/musicList/AllMusicList.qml
- Add isPlayAll property to control play button state
- Update translations for multiple languages in deepin-music
- Improve music player interface text across all locales
Log: add isPlayAll property and update translations
Bug: https://pms.uniontech.com/bug-view-289899.html
> fix: add isPlayAll property and update translations

- src/music-player/albumlist/AlbumView.qml
- src/music-player/musicbaseandsonglist/SideBarItemDelegate.qml
- src/music-player/singerlist/ArtistView.qml
- Add playAll button state check in Album and Artist views
- Adjust LineEdit width and alignment in sidebar item delegate
Log: update UI components layout and playAll button state
Bug: https://pms.uniontech.com/bug-view-281269.html
> fix: update UI components layout and playAll button state

- src/music-player/musicsublist/AlbumSublistView.qml
- src/music-player/musicsublist/ArtistSublistView.qml
- src/music-player/musicsublist/MusicSublistModel.qml
- Add loading state tracking in MusicSublistModel
- Add data change handlers in Album and Artist views
- Prevent premature view navigation during data loading
- Add null checks for media data map
Log: improve data loading in album and artist sublist views
Bug: https://pms.uniontech.com/bug-view-275597.html
> fix: improve data loading in album and artist sublist views

- arm64/linglong.yaml
- debian/changelog
- linglong.yaml
- loong64/linglong.yaml
- translations/deepin-music_zh_CN.ts
- translations/deepin-music_zh_HK.ts
- translations/deepin-music_zh_TW.ts
update translations
Log: update translations
> chore: update translations
